#!/bin/bash

# Get the absolute directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RUN_SCRIPT="$SCRIPT_DIR/run.sh"

# Ensure run.sh is executable
chmod +x "$RUN_SCRIPT"

# Path to zsh configuration file
ZSHRC="$HOME/.zshrc"
COMMAND_NAME="make-caffeine-pkg"

# Check if the alias is already defined in .zshrc
if grep -q "alias $COMMAND_NAME=" "$ZSHRC"; then
    echo "Command '$COMMAND_NAME' is already defined in $ZSHRC"
    exit 0
fi

# Append to .zshrc
echo "" >> "$ZSHRC"
echo "# Generated by Caffeine Package Tool CLI" >> "$ZSHRC"
echo "alias $COMMAND_NAME='$RUN_SCRIPT'" >> "$ZSHRC"

echo "Alias '$COMMAND_NAME' added to $ZSHRC"
echo "To use the new command, run: source ~/.zshrc"
